debug: false

certManager:
  enabled: true
  spec:
    project: default
    sources:
      - chart: 'cert-manager'
        repoURL: https://charts.jetstack.io
        targetRevision: "1.14.3"
        helm:
          releaseName: "cert-manager"
          ignoreMissingValueFiles: true
          valueFiles: []
          values: |
            installCRDs: true
    destination:
      namespace: 'cert-manager'
      name: 'in-cluster'
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

istioBase:
  enabled: true
  spec:
    project: default
    sources:
      - chart: 'base'
        repoURL: 'https://istio-release.storage.googleapis.com/charts'
        targetRevision: "1.18.7"
        helm:
          releaseName: "istio-base"
          ignoreMissingValueFiles: true
          valueFiles: []
    destination:
      namespace: 'istio-system'
      name: 'in-cluster'
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

istiod:
  enabled: true
  spec:
    project: default
    sources:
      - chart: 'istiod'
        repoURL: 'https://istio-release.storage.googleapis.com/charts'
        targetRevision: "1.18.7"
        helm:
          releaseName: "istiod"
          ignoreMissingValueFiles: true
          valueFiles: []
          values: |
            pilot:
              resources:
                requests:
                  cpu: 10m
                  memory: 128Mi
            global:
              proxy:
                resources:
                  requests:
                    cpu: 10m
                    memory: 64Mi
    destination:
      namespace: 'istio-system'
      name: 'in-cluster'
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

gateway:
  enabled: true
  spec:
    project: default
    sources:
      - chart: 'gateway'
        repoURL: 'https://istio-release.storage.googleapis.com/charts'
        targetRevision: "1.18.7"
        helm:
          releaseName: "istio-ingressgateway"
          ignoreMissingValueFiles: true
          valueFiles: []
          values: |
            service:
              type: ClusterIP
            serviceAccount:
              name: istio-ingressgateway-service-account
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                cpu: 2000m
                memory: 1024Mi
    destination:
      namespace: 'istio-system'
      name: 'in-cluster'
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

dex:
  enabled: true
  spec:
    project: default
    source:
      path: common/dex/overlays/istio
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

oidcAuthService:
  enabled: true
  spec:
    project: default
    source:
      path: common/oidc-client/oidc-authservice/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

kubeflowNamespace:
  enabled: true
  spec:
    project: default
    source:
      path: common/kubeflow-namespace/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

istioResources:
  enabled: true
  spec:
    project: default
    source:
      path: common/istio-1-17/kubeflow-istio-resources/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

kubeflowRoles:
  enabled: true
  spec:
    project: default
    source:
      path: common/kubeflow-roles/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

admissionWebhook:
  enabled: true
  spec:
    project: default
    source:
      path: apps/admission-webhook/upstream/overlays/cert-manager
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

centralDashboard:
  enabled: true
  spec:
    project: default
    source:
      path: apps/centraldashboard/upstream/overlays/kserve
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
      kustomize:
        patches:
        - target:
            kind: ConfigMap
            name: centraldashboard-config
          patch: |-
            - op: replace
              path: /data/links
              value: |
                {
                  "menuLinks": [
                    {
                      "type": "item",
                      "link": "/jupyter/",
                      "text": "Notebooks",
                      "icon": "book"
                    },
                    {
                      "type": "item",
                      "link": "/volumes/",
                      "text": "Volumes",
                      "icon": "device:storage"
                    }
                  ],
                  "externalLinks": [ ],
                    "quickLinks": [
                      {
                        "text": "Create a new Notebook server",
                        "desc": "Notebook Servers",
                        "link": "/jupyter/new?namespace=kubeflow"
                      }
                    ],
                    "documentationItems": [
                      {
                        "text": "Getting Started with Kubeflow",
                        "desc": "Get your machine-learning workflow up and running on Kubeflow",
                        "link": "https://www.kubeflow.org/docs/started/getting-started/"
                      }
                    ]
                }
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

jupyterWebApp:
  enabled: true
  spec:
    project: default
    source:
      path: apps/jupyter/jupyter-web-app/upstream/overlays/istio
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

notebookController:
  enabled: true
  spec:
    project: default
    source:
      path: apps/jupyter/notebook-controller/upstream/overlays/kubeflow
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

profiles:
  enabled: true
  spec:
    project: default
    source:
      path: apps/profiles/upstream/overlays/kubeflow
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

pvcViewerController:
  enabled: true
  spec:
    project: default
    source:
      path: apps/pvcviewer-controller/upstream/default
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

volumesWebApp:
  enabled: true
  spec:
    project: default
    source:
      path: apps/volumes-web-app/upstream/overlays/istio
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

exampleProfile:
  enabled: true
  spec:
    project: default
    source:
      path: common/user-namespace/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

knativeServing:
  enabled: false
  spec:
    project: default
    source:
      path: common/knative/knative-serving/overlays/gateways
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
      kustomize:
        patches:
        - target:
            kind: Deployment
            name: activator
            namespace: knative-serving
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/resources/requests/cpu
              value: 15m
        - target:
            kind: Deployment
            name: autoscaler
            namespace: knative-serving
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/resources/requests/cpu
              value: 15m
        - target:
            kind: Deployment
            name: domainmapping-webhook
            namespace: knative-serving
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/resources/requests/cpu
              value: 15m
        - target:
            kind: Deployment
            name: webhook
            namespace: knative-serving
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/resources/requests/cpu
              value: 15m
        - target:
            kind: Deployment
            name: controller
            namespace: knative-serving
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/resources/requests/cpu
              value: 15m
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

clusterLocalGateway:
  enabled: false
  spec:
    project: default
    source:
      path: common/istio-1-17/cluster-local-gateway/base
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
      kustomize:
        patches:
        - target:
            kind: Deployment
            name: cluster-local-gateway
            namespace: istio-system
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/resources/requests/cpu
              value: 10m
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

kserve:
  enabled: false
  spec:
    project: default
    source:
      path: contrib/kserve/kserve
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
      kustomize:
        patches:
        - target:
            kind: Deployment
            name: kserve-controller-manager
            namespace: kubeflow
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/resources/requests/cpu
              value: 15m
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

katib:
  enabled: false
  spec:
    project: default
    source:
      path: apps/katib/upstream/installs/katib-with-kubeflow
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

modelsWebApp:
  enabled: false
  spec:
    project: default
    source:
      path: contrib/kserve/models-web-app/overlays/kubeflow
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

kubeflowPipelines:
  enabled: false
  spec:
    project: default
    source:
      path: apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
      kustomize:
        patches:
        - target:
            kind: Deployment
            name: ml-pipeline
            namespace: kubeflow
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/resources/requests/cpu
              value: 10m
        - target:
            kind: Deployment
            name: ml-pipeline-persistenceagent
            namespace: kubeflow
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/resources/requests/cpu
              value: 10m
        - target:
            kind: Deployment
            name: workflow-controller
            namespace: kubeflow
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/resources/requests/cpu
              value: 10m
        - target:
            kind: Deployment
            name: mysql
            namespace: kubeflow
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/resources/requests/cpu
              value: 10m
        - target:
            kind: StatefulSet
            name: metacontroller
            namespace: kubeflow
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/resources/requests/cpu
              value: 10m
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

tensorboardController:
  enabled: false
  spec:
    project: default
    source:
      path: apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

tensorboardsWebApp:
  enabled: false
  spec:
    project: default
    source:
      path: apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
      repoURL: https://github.com/kubeflow/manifests
      targetRevision: 776d4f4
    destination:
      namespace: argocd
      name: in-cluster
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - ServerSideApply=true

kuberay:
  enabled: false
  spec:
    project: default
    sources:
      - chart: 'kuberay-operator'
        repoURL: 'https://ray-project.github.io/kuberay-helm/'
        targetRevision: "1.1.0"
        helm:
          releaseName: "kuberay"
          ignoreMissingValueFiles: true
          valuesObject:
            resources: {}
    destination:
      namespace: 'kubeflow'
      name: 'in-cluster'
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

sparkOperator:
  enabled: false
  spec:
    project: default
    sources:
      - chart: 'spark-operator'
        repoURL: 'https://kubeflow.github.io/spark-operator'
        targetRevision: "1.1.27"
        helm:
          releaseName: "spark-operator"
          ignoreMissingValueFiles: true
          valuesObject: {}
    destination:
      namespace: 'kubeflow'
      name: 'in-cluster'
    syncPolicy:
      automated:
        prune: false
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true